<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tecnología y Desarrollo de Aproscello">
<meta name="dcterms.date" content="2024-12-11">

<title>SUPREMA FL</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Suprema FL Referencial de manejo_files/libs/clipboard/clipboard.min.js"></script>
<script src="Suprema FL Referencial de manejo_files/libs/quarto-html/quarto.js"></script>
<script src="Suprema FL Referencial de manejo_files/libs/quarto-html/popper.min.js"></script>
<script src="Suprema FL Referencial de manejo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Suprema FL Referencial de manejo_files/libs/quarto-html/anchor.min.js"></script>
<link href="Suprema FL Referencial de manejo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Suprema FL Referencial de manejo_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Suprema FL Referencial de manejo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Suprema FL Referencial de manejo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Suprema FL Referencial de manejo_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #000000;
      }

      .quarto-title-block .quarto-title-banner {
        color: #000000;
background: #67EBA9;
      }
</style>


</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">SUPREMA FL</h1>
            <p class="subtitle lead">REFERENCIAL DE MANEJO AGRONÓMICO</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><strong>Tecnología y Desarrollo de Aproscello</strong> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 11, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#suprema-fl" id="toc-suprema-fl" class="nav-link active" data-scroll-target="#suprema-fl">SUPREMA FL</a>
  <ul class="collapse">
  <li><a href="#características-agronómicas" id="toc-características-agronómicas" class="nav-link" data-scroll-target="#características-agronómicas"><strong>Características agronómicas</strong></a></li>
  <li><a href="#reacción-a-plagas-y-enfermedades" id="toc-reacción-a-plagas-y-enfermedades" class="nav-link" data-scroll-target="#reacción-a-plagas-y-enfermedades"><strong>Reacción a plagas y enfermedades</strong></a></li>
  <li><a href="#características-de-la-semilla" id="toc-características-de-la-semilla" class="nav-link" data-scroll-target="#características-de-la-semilla"><strong>Características de la semilla</strong></a></li>
  </ul></li>
  <li><a href="#referencial-de-manejo-agronómico" id="toc-referencial-de-manejo-agronómico" class="nav-link" data-scroll-target="#referencial-de-manejo-agronómico"><strong>REFERENCIAL DE MANEJO AGRONÓMICO</strong></a>
  <ul class="collapse">
  <li><a href="#densidad-de-siembra" id="toc-densidad-de-siembra" class="nav-link" data-scroll-target="#densidad-de-siembra"><strong>Densidad de siembra</strong></a></li>
  <li><a href="#control-de-malezas" id="toc-control-de-malezas" class="nav-link" data-scroll-target="#control-de-malezas"><strong>Control de malezas</strong></a></li>
  <li><a href="#manejo-de-la-fertilización" id="toc-manejo-de-la-fertilización" class="nav-link" data-scroll-target="#manejo-de-la-fertilización"><strong>Manejo de la fertilización</strong></a></li>
  <li><a href="#manejo-de-enfermedades" id="toc-manejo-de-enfermedades" class="nav-link" data-scroll-target="#manejo-de-enfermedades"><strong>Manejo de enfermedades</strong></a></li>
  <li><a href="#manejo-del-riego" id="toc-manejo-del-riego" class="nav-link" data-scroll-target="#manejo-del-riego"><strong>Manejo del riego</strong></a></li>
  <li><a href="#cosecha" id="toc-cosecha" class="nav-link" data-scroll-target="#cosecha"><strong>Cosecha</strong></a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="logo.png" title="Aproscello" class="quarto-figure quarto-figure-left figure-img" width="118" height="56"></p>
<figcaption>Rif: J-08507040-0</figcaption>
</figure>
</div>
<section id="suprema-fl" class="level2">
<h2 class="anchored" data-anchor-id="suprema-fl">SUPREMA FL</h2>
<p>Le presentamos a todos los productores de arroz de Venezuela nuestra nueva variedad de arroz <strong><em>SUPREMA FL</em></strong> con características que la diferencia del resto de las variedades comerciales que están disponibles en mercado.</p>
<p>La <strong><em>Comisión Nacional de Semilla</em></strong> (CONASEM), le asignó el código Nº <strong><em>CNS-CC-22-502-12</em></strong> en el <strong><em>Registro Nacional de Cultivares Comerciales</em></strong>.</p>
<p>La variedad <strong><em>SUPREMA FL</em></strong>, proviene del cruce de FL05512-7P-6-1P/FL02066-4P-1-1P-2P-M-1P-M-M-M-F11//FL04574-1P-4-3P-1P-M y tiene por <em>Pedigree FL08310-4P-1-3P-3P-M-2PY-M</em>.</p>
<p>Fue obtenida en el <strong><em>Fondo Latinoamericano de Arroz de Riego</em></strong> (FLAR) durante las generaciones segregantes F2 a F5; luego fue seleccionada y desarrollada por el programa de mejoramiento de la <strong><em>Asociación de Productores de Semilla Certificada de los Llanos Occidentales</em></strong> (APROSCELLO) con el apoyo de la <strong><em>Fundación Nacional del Arroz</em></strong> (FUNDARROZ).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="AP009-8.jpeg" title="Desarrollo de variedades" class="img-fluid figure-img"></p>
<figcaption>Suprema FL, durante la fase de desarrollo de variedades</figcaption>
</figure>
</div>
<hr>
<section id="características-agronómicas" class="level3">
<h3 class="anchored" data-anchor-id="características-agronómicas"><strong>Características agronómicas</strong></h3>
<table class="table-striped table-hover table">
<tbody>
<tr class="odd">
<td>Altura de la planta (cm)</td>
<td style="text-align: center;">98 - 105</td>
</tr>
<tr class="even">
<td>Ciclo</td>
<td style="text-align: center;">Intermedio (115-120 días)</td>
</tr>
<tr class="odd">
<td>Hábito de crecimiento</td>
<td style="text-align: center;">Semi-compacto</td>
</tr>
<tr class="even">
<td>Macollamiento</td>
<td style="text-align: center;">Buena capacidad</td>
</tr>
<tr class="odd">
<td>Color de la hoja</td>
<td style="text-align: center;">Verde</td>
</tr>
<tr class="even">
<td>Reacción al desgrane</td>
<td style="text-align: center;">Moderadamente difícil</td>
</tr>
<tr class="odd">
<td>Reacción al volcamiento</td>
<td style="text-align: center;">Resistente</td>
</tr>
<tr class="even">
<td>Tallo</td>
<td style="text-align: center;">Fuerte y flexible</td>
</tr>
<tr class="odd">
<td>Fertilidad (%)</td>
<td style="text-align: center;">90.58 - 97.51</td>
</tr>
<tr class="even">
<td>Nº de Granos por panícula</td>
<td style="text-align: center;">176 - 237</td>
</tr>
<tr class="odd">
<td>Longitud de la panícula (cm)</td>
<td style="text-align: center;">23.5 - 32.1</td>
</tr>
<tr class="even">
<td>Retraso a cosecha</td>
<td style="text-align: center;">Resistente</td>
</tr>
<tr class="odd">
<td>Potencial de rendimiento (TN/ha)</td>
<td style="text-align: center;">Superior a 8,5</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="reacción-a-plagas-y-enfermedades" class="level3">
<h3 class="anchored" data-anchor-id="reacción-a-plagas-y-enfermedades"><strong>Reacción a plagas y enfermedades</strong></h3>
<table class="table-striped table-hover table">
<tbody>
<tr class="odd">
<td>Piricularia hoja (<em>Pyricularia oryzae</em> )</td>
<td style="text-align: center;">0 - 3</td>
</tr>
<tr class="even">
<td>Piricularia cuello (<em>Pyricularia oryzae</em> )</td>
<td style="text-align: center;">0 - 3</td>
</tr>
<tr class="odd">
<td>Helminthosporiosis en hoja (<em>Helminthosporium oryzae</em>)</td>
<td style="text-align: center;">0 - 3</td>
</tr>
<tr class="even">
<td>Helminthosporiosis en cuello (<em>Helminthosporium oryzae</em>)</td>
<td style="text-align: center;">0 - 3</td>
</tr>
<tr class="odd">
<td>Escaldado (<em>Rhynchosporium oryzae</em>)</td>
<td style="text-align: center;">0 - 3</td>
</tr>
<tr class="even">
<td>Manchado del grano</td>
<td style="text-align: center;">0 - 3</td>
</tr>
<tr class="odd">
<td>Virus Hoja Blanca</td>
<td style="text-align: center;">0 - 5</td>
</tr>
<tr class="even">
<td>Sogata (<em>Tagosodes orizicolus</em>)</td>
<td style="text-align: center;">0 - 3</td>
</tr>
</tbody>
</table>
<ul>
<li><p>La escala de medición va desde 0 a 9.</p>
<ul>
<li><p>0 significa que no presentó síntomas y es resistente.</p></li>
<li><p>9 es altamente susceptible.</p></li>
</ul></li>
</ul>
<hr>
</section>
<section id="características-de-la-semilla" class="level3">
<h3 class="anchored" data-anchor-id="características-de-la-semilla"><strong>Características de la semilla</strong></h3>
<table class="table-striped table-hover table">
<tbody>
<tr class="odd">
<td>Longitud mm)</td>
<td style="text-align: center;">9.0 - 11.0</td>
</tr>
<tr class="even">
<td>Ancho (mm)</td>
<td style="text-align: center;">2.0 - 3.0</td>
</tr>
<tr class="odd">
<td>Espesor (mm)</td>
<td style="text-align: center;">2.0</td>
</tr>
<tr class="even">
<td>Arista</td>
<td style="text-align: center;">Ausente</td>
</tr>
<tr class="odd">
<td>Peso de 1000 semillas (gr)</td>
<td style="text-align: center;">24.0 - 28.0</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="referencial-de-manejo-agronómico" class="level2">
<h2 class="anchored" data-anchor-id="referencial-de-manejo-agronómico"><strong>REFERENCIAL DE MANEJO AGRONÓMICO</strong></h2>
<p>El <em>Referencial de Manejo Agronómico de la variedad <strong>SUPREMA FL</strong></em> constituye una guía imprescindible para garantizar la optimización de su manejo en campo y ayudará a que el productor alcance altos rendimientos. Recomendamos que tanto agrotécnicos como los productores estudien con detenimiento cada una de estas recomendaciones que aun cuando son de carácter general, resultan suficientes como base orientativa para la toma de decisiones en cada fase de desarrollo del cultivo.</p>
<hr>
<section id="densidad-de-siembra" class="level3">
<h3 class="anchored" data-anchor-id="densidad-de-siembra"><strong>Densidad de siembra</strong></h3>
<p>En nuestras evaluaciones experimentales y semicomerciales se determinó que la SUPREMA FL puede ser manejada bajo diferentes densidades de siembra, sin embargo, para definir la cantidad de semilla por hectárea recomendamos sopesar la modalidad de siembra a implementar; a continuación hacemos las consideraciones pertinentes para cada sistema.</p>
<section id="sistema-de-barro-batido-y-semilla-pregerminada" class="level4">
<h4 class="anchored" data-anchor-id="sistema-de-barro-batido-y-semilla-pregerminada"><strong><em>Sistema de barro batido y semilla pregerminada</em></strong></h4>
<p>Al igual que otras variedades comerciales, recomendamos que el pregerminado se realice dándole una primera fase de remojo que puede durar entre 24 a 36 horas y durante una segunda fase, luego de sacar la semilla del agua colocar la semilla bajo sombra durante un tiempo no menor de 24 horas y no mayor de 28 horas, al finalizar esta segunda fase, la semilla estará lista la siembra. Consideramos que el productor maneje densidades de entre 90 y 120 kg/ha de semilla certificada. A nivel comercial le damos preferencia a usar 100 kg/ha.</p>
</section>
<section id="sistemas-de-labranza-en-suelo-seco-y-otros-alternativos" class="level4">
<h4 class="anchored" data-anchor-id="sistemas-de-labranza-en-suelo-seco-y-otros-alternativos"><strong><em>Sistemas de labranza en suelo seco y otros alternativos</em></strong></h4>
<p>En sistemas de labranza reducida o conservacionista, recomendamos densidades de entre los 60 y 90 kg/ha de semilla certificada; algunas consideraciones importantes son las siguientes:</p>
<ul>
<li><p>Profundidad de siembra en 2,5 cm de promedio y que ésta no sea mayor a 3 cm.</p></li>
<li><p>Si la siembra es bajo el esquema de semilla tapada con rastra de tiro, se recomendamos incrementar entre un 5 % a 7 % la densidad con el propósito de compensar la pérdida por las semillas que queden muy profunda y no son capaces de emerger.</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="AP009-5.jpeg" title="Suprema FL" class="img-fluid figure-img"></p>
<figcaption>Suprema FL, sembrada a 80 kg/ha</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="control-de-malezas" class="level3">
<h3 class="anchored" data-anchor-id="control-de-malezas"><strong>Control de malezas</strong></h3>
<p>Como componente fundamental del manejo integral del cultivo hemos sometido a evaluación el comportamiento de la SUPREMA FL frente a las principales moléculas de herbicidas que se utilizan en el cultivo de arroz utilizando las dosis recomendadas utilizando los productos solos y en mezclas tradicionales. Durante la implementación de las pruebas se realizaron aplicaciones en condiciones de ambiente controlado, así como en parcelas semicomerciales para validar en condiciones de campo, se consideraron testigos absolutos y mezclas tradicionales de herbicidas con preemergentes, postemergentes, de contacto y sistémicos. Como resultado se pudo observar que la variedad <strong><em>SUPREMA FL</em></strong> no mostró problemas de fitotoxicidad ni afecciones en el desarrollo normal del cultivo.</p>
<p>A continuación algunos tips de importancia en el control de malezas con herbicidas:</p>
<ul>
<li><p>Cuando se utilice semilla pregerminada, se recomienda que los controles de malezas se realicen en pre-emergencia temprana, esto es, entre los 5 y 10 dds (días después de la siembra).</p></li>
<li><p>En el caso de usar semilla seca (no pregerminada) es completamente viable realizar aplicaciones de control de malezas entre los primeros 3 días antes de la emergencia; sin embargo, es importante que la decisión sea avalada por un técnico que verifique el estado de avance de la etapa de germinación para no salirse del momento óptimo de aplicación.</p></li>
<li><p>Recuerde que en mezcla donde estén presentes propaniles no deben agregarse o mezclarse insecticidas fosforados o carbamatos.</p></li>
</ul>
<hr>
</section>
<section id="manejo-de-la-fertilización" class="level3">
<h3 class="anchored" data-anchor-id="manejo-de-la-fertilización"><strong>Manejo de la fertilización</strong></h3>
<p>La fertilización es unas de las labores más importantes debido que está asociada al óptimo desarrollo del cultivo y la mayor expresión del potencial de rendimiento del cultivo de arroz. Durante la etapa de desarrollo de la variedad SUPREMA FL, nos esforzamos en obtener el patrón de extracción de nitrógeno, fósforo y potasio por vía indirecta.</p>
<p>Recomendamos no improvisar en el diseño y la aplicación del plan de fertilización a fin de garantizar la mejor nutrición posible y lograr el uso eficiente de los fertilizante. La base para armar el plan es partir de un análisis de suelo que permita conocer sus propiedades físico-químicas, así mismo considerar la interacción entre la fecha de aplicación (momento oportuno), el tipo de nutriente o elemento a aplicar y las dosis.</p>
<p>Nos atrevemos a proponer una plan de fertilización de referencia tomando en cuenta los resultados de los ensayos realizados en cada zona y la demanda de NPK específica mostrada por la variedad, sin embargo, no olvide realizar una análisis riguroso de la información para ajustar los niveles de enmienda.</p>
<hr>
<p><strong>Tabla base para estimar necesidades nutricionales de la variedad</strong></p>
<table class="table-striped table-hover table">
<thead>
<tr class="header">
<th>Elemento</th>
<th style="text-align: center;">Cantidad kg/ha</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nitrógeno (N)</td>
<td style="text-align: center;">160 a 180</td>
</tr>
<tr class="even">
<td>Fósforo (P<sub>2</sub>O<sub>5</sub>)</td>
<td style="text-align: center;">25 a 31</td>
</tr>
<tr class="odd">
<td>Potasio (K<sub>2</sub>O)</td>
<td style="text-align: center;">115 a 122</td>
</tr>
</tbody>
</table>
<hr>
<p><strong>1ra. Propuesta de fertilización con fósforo y potasio incorporados y dos reabonos</strong></p>
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 45%">
<col style="width: 24%">
<col style="width: 18%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Momento</th>
<th>Fuente</th>
<th>Elementos</th>
<th>Cantidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Presiembra incorporado</td>
<td>Fósfoto diamónico</td>
<td>Fósforo (P)</td>
<td>Todo</td>
</tr>
<tr class="even">
<td>Presiembra incorporado</td>
<td>Cloruro de potasio</td>
<td>Potasio (K)</td>
<td>Todo</td>
</tr>
<tr class="odd">
<td>Reabono entre los 16 a 20 dds o dde</td>
<td>Urea</td>
<td>Nitrógeno (N)</td>
<td>60%</td>
</tr>
<tr class="even">
<td>Reabono entre los 40 a 45 dds o dde</td>
<td>Urea</td>
<td>Nitrógeno (N)</td>
<td>40%</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>dds = días después de la siembra; dde = días después de la emergencia</p>
</blockquote>
<hr>
<p><strong>2da. Propuesta de fertilización en base a modalidad tradicional</strong></p>
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 45%">
<col style="width: 24%">
<col style="width: 18%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Momento</th>
<th>Fuente</th>
<th>Elementos</th>
<th>Cantidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Básica entre los 25 a 30 dds o dde</td>
<td>Fórmula completa</td>
<td>Nitrógeno (N)</td>
<td>20%</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Fósforo (P)</td>
<td>Todo</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>Potasio (P)</td>
<td>20%</td>
</tr>
<tr class="even">
<td>Reabono entre los 25 a 32 dds o dde</td>
<td>Urea</td>
<td>Nitrógeno (N)</td>
<td>45%</td>
</tr>
<tr class="odd">
<td></td>
<td>Cloruro de potasio</td>
<td>Potasio (K)</td>
<td>80%</td>
</tr>
<tr class="even">
<td>Reabono a los 45 dds o dde</td>
<td>Urea</td>
<td>Nitrógeno (N)</td>
<td>40%</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>dds = días después de la siembra; dde = días después de la emergencia</p>
</blockquote>
<hr>
<p>Las cantidades de fertilizante expresadas en porcentaje (%) del total respectivo, no es una camisa de fuerza, sin embargo, debe usarse cantidades que se acerquen a esos valores, entendiendo que todo va a depender del total requerido por nutriente y la proporción del mismo presente en la fuente utilizada.</p>
<p>Es importante resaltar que consideramos válido que si por razones de logística la última enmienda de <strong><em>nitrógeno</em></strong> no se pudiera aplicar antes de la etapa de elongación, se recomienda esperar que esta etapa termine para poder realizarla, esto evitará que la planta crezca en altura por encima de su promedio lo que induciría a condiciones favorables para el acame o vuelco. igual consideración debe tenerse en caso que el técnico recomiende suplir un adicional de nitrógeno.</p>
<p>A continuación agregamos información complementaria sobre la fertilización:</p>
<ul>
<li><p><strong>Nitrógeno (N):</strong> No aplicar menos de 160 unidades/ha; no perder de vista la relación 1:1 con el potasio (K).</p></li>
<li><p><strong>Fósforo (P):</strong> el cultivar mostró que para alcanzar un rendimiento superior a las 8 toneladas/ha, requirió la absorción de 31 kg/ha de P<sub>2</sub>O<sub>5</sub>, en base a esta información se recomienda un promedio de 22 unidades/ha de P<sub>2</sub>O<sub>5</sub>, sin embargo, esta cantidad debe ser ajustada en función de la disponibilidad del elemento en el suelo.</p></li>
<li><p><strong>Potasio (K):</strong> este elemento está relacionado con la sanidad integral del cultivar, la producción de materia seca y su potencial de rendimiento. El patrón de extracción determinado indirectamente mostró que las mejores respuestas en rendimiento de grano se alcanzaron con enmiendas de entre los 115 y 122 kg/ha de K<sub>2</sub>O; resaltamos que se pondere su aplicación en base al análisis de suelo y la dinámica del elemento en su relación con el nitrógeno (N) y el magnesio (Mg).</p></li>
<li><p><strong>Calcio, Magnesio y Azufre:</strong> estos tres elementos juegan un importante papel dentro del desarrollo del cultivo y es importante considerar su enmienda para garantizar su equilibrio. Sin embargo, debemos que señalar que no ha sido posible determinar sus patrones de extracción, por lo que lo recomendado a continuación se basa en referencias de otros trabajos similares en arroz.</p>
<ul>
<li><p>Calcio: entre 11 y 16 kg/ha de Ca, preferiblemente con la fertilización básica.</p></li>
<li><p>Magnesio: entre 8 y 12 kg/ha de Mg en la fertilización básica o en el primer reabono.</p></li>
<li><p>Azufre: 16 y 22 kg/ha de S; preferiblemente en el primer reabono.</p></li>
</ul></li>
</ul>
<hr>
</section>
<section id="manejo-de-enfermedades" class="level3">
<h3 class="anchored" data-anchor-id="manejo-de-enfermedades"><strong>Manejo de enfermedades</strong></h3>
<p>La variedad <strong><em>SUPREMA FL</em></strong> fue evaluada con el rigor necesario en diferentes ambientes para conocer su comportamiento frente a las enfermedades fungosas más importantes del país (ver el apartado <em>Reacción frente a plagas y enfermedades)</em>. Aun cuando su desempeño fue muy bueno frente a los patógenos más importantes, es necesario tener presente que ante las variaciones climáticas que se están presentando en los últimos años hay que estar atentos a las diferentes síntomas que se puedan presentar y recomendamos que durante los meses del año donde se registran constantes precipitaciones y altas temperaturas, se realice bajo asesoría técnica protecciones preventivas con fungicidas dirigidas a garantizar la sanidad integral de cultivo y en especial de las panículas , de esta manera se evitaría posibles brotes del complejo de patógenos responsable del manchado de granos.</p>
<div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="AP009-9.jpeg" class="img-fluid figure-img" width="1280"></p>
<figcaption>En fase reproductiva</figcaption>
</figure>
</div>
</div>
<hr>
</section>
<section id="manejo-del-riego" class="level3">
<h3 class="anchored" data-anchor-id="manejo-del-riego"><strong>Manejo del riego</strong></h3>
<p>La variedad <strong>SUPREMA</strong> <strong><em>FL</em></strong> no demanda el establecimiento de láminas de agua por largos periodos de tiempo. Al igual las demás variedades que se comercializan en la actualidad, puede ser manejada con mojes en la fase vegetativa y solo durante las etapas correspondiente a la fase reproductiva recomendamos que se establezca la lámina para garantizar el normal desarrolla de de emergencia de panículas, floración, grano lechoso y grano pastoso. Estas etapas son críticas para definir un buen llenado y calidad de grano.</p>
<hr>
</section>
<section id="cosecha" class="level3">
<h3 class="anchored" data-anchor-id="cosecha"><strong>Cosecha</strong></h3>
<p><strong><em>SUPREMA FL</em></strong> puede tolerar retrasos a la cosecha, siendo una característica importante por los diferentes factores que pueden interferir al momento de ejecutar la recolección del grano (lluvia, logística de cosecha, accidentes de maquinaria entre otros).</p>
<p>Recomendamos que se revise periódicamente la calibración de la cosechadora combinada para reducir las pérdidas que con frecuencia suceden durante esta importante tarea.</p>
<p>Humedad del grano ideal para la recolección: entre 22% y 20%.</p>
<hr>
<p>Si tiene preguntas o dudas sobre la información de manejo de la <strong><em>SUPREMA FL</em></strong>, no dude en consultarnos a los correos:</p>
<ul>
<li><p><a href="mailto:aproscello@gmail.com">aproscello@gmail.com</a></p></li>
<li><p><a href="mailto:orlandoinvestiga@gmail.com">orlandoinvestiga@gmail.com</a></p>
<p>… y con mucho gusto ampliaremos la información.</p></li>
</ul>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="logo.png" class="img-fluid quarto-figure quarto-figure-left figure-img" width="146"></p>
<figcaption>Rif: J-08507040-0</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div>
<p><strong>Ing. Yuraima Mendoza</strong></p>
<p><em>Fitomejoradora</em></p>
</div>
<div>
<p><strong>Ing. Msc. Orlando Pérez</strong></p>
<p><em>Gerente de Tecnología y Desarrollo</em></p>
</div>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>